apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecutive:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1a
            - us-east-1b
            - us-east-1c
            - us-east-1d
            # scheduler checks the above 4 availibilty zone and keeps the pod in node
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always