apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-3
spec:
  affinity:
    podAntiAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution:
        # pod labels
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - pod-affinity-1
            - pod-affinity-2
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always